# -*- coding: utf-8 -*-
"""P12_application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xb7klKtaaKHzL3ytPFNAq4CJOXvPCnHT
"""

import pandas as pd
import joblib
import os
import argparse
import sys

# Conditional import for display (for interactive environments like Colab)
try:
    from IPython.display import display as ipython_display
except ImportError:
    # Define a dummy display function for environments where IPython.display is not available
    def ipython_display(*args, **kwargs):
        if args:
            print(args[0]) # Fallback to print if display is not available

def predict_bill_authenticity_from_csv(new_csv_file_path: str, model_path: str = 'best_logistic_regression_model.joblib') -> pd.DataFrame:
    """
    Loads a pre-trained machine learning model, reads new bill data from a CSV,
    and predicts the authenticity of bills.

    Args:
        new_csv_file_path (str): Path to the CSV file containing new bill data.
                                   Expected columns are 'diagonal', 'height_right',
                                   'height_left', 'margin_up', 'margin_low', 'length'.
                                   An 'id' column is optional.
        model_path (str): Path to the saved model file.

    Returns:
        pd.DataFrame: A DataFrame with the 'id' (if present in input) and the
                      predicted authenticity ('is_genuine_predicted').
                      Returns an empty DataFrame on error.
    """
    # 1. Vérifier l'existence du fichier CSV
    if not os.path.exists(new_csv_file_path):
        print(f"Erreur: Le fichier CSV '{new_csv_file_path}' est introuvable.")
        return pd.DataFrame()

    # 2. Charger le modèle sauvegardé
    try:
        model = joblib.load(model_path)
        print(f"Modèle chargé depuis : {model_path}")
    except FileNotFoundError:
        print(f"Erreur: Le fichier modèle '{model_path}' est introuvable. Assurez-vous qu'il est dans le bon répertoire.")
        return pd.DataFrame()
    except Exception as e:
        print(f"Erreur lors du chargement du modèle: {e}")
        return pd.DataFrame()

    # 3. Charger les nouvelles données
    try:
        df_new_bills = pd.read_csv(new_csv_file_path)
        print(f"Nouvelles données chargées depuis '{new_csv_file_path}'. Aperçu:")
        # Check if running in an interactive environment (like Colab) to use ipython_display
        if 'ipykernel' in sys.modules or hasattr(sys, 'ps1'):
            ipython_display(df_new_bills.head())
        else:
            print(df_new_bills.head()) # Use print for command line
    except Exception as e:
        print(f"Erreur lors du chargement du fichier CSV '{new_csv_file_path}': {e}")
        return pd.DataFrame()

    # 4. Préparer les données pour la prédiction
    bill_ids = None
    if 'id' in df_new_bills.columns:
        bill_ids = df_new_bills['id']
        X_new = df_new_bills.drop(columns=['id'])
    else:
        # Si pas d'ID, en créer un simple pour le DataFrame de résultats
        bill_ids = pd.Series(range(len(df_new_bills)), name='id')
        X_new = df_new_bills.copy()

    # Les colonnes attendues par le modèle (basées sur l'entraînement)
    expected_columns = ['diagonal', 'height_right', 'height_left', 'margin_up', 'margin_low', 'length']

    # Vérifier si toutes les colonnes requises sont présentes
    if not all(col in X_new.columns for col in expected_columns):
        missing_cols = [col for col in expected_columns if col not in X_new.columns]
        print(f"Erreur: Les colonnes suivantes sont manquantes dans '{new_csv_file_path}': {missing_cols}")
        return pd.DataFrame()

    # S'assurer que l'ordre des colonnes est le même que celui utilisé lors de l'entraînement
    X_new = X_new[expected_columns]

    # 5. Effectuer les prédictions
    # Le pipeline (inclus dans le modèle joblib) gérera la mise à l'échelle et l'imputation si nécessaire
    y_pred = model.predict(X_new)

    # 6. Créer le DataFrame des résultats
    df_predictions = pd.DataFrame({'id': bill_ids, 'is_genuine_predicted': y_pred})
    return df_predictions

# Bloc pour permettre l'exécution directe depuis la ligne de commande
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Prédire l'authenticité de billets à partir d'un fichier CSV.")
    parser.add_argument('--csv_path', type=str, required=True,
                        help="Chemin d'accès au fichier CSV contenant les nouvelles données de billets.")
    parser.add_argument('--model_path', type=str, default='best_logistic_regression_model.joblib',
                        help="Chemin d'accès au fichier du modèle sauvegardé (par défaut: best_logistic_regression_model.joblib).")

    # Check if running in an interactive environment (like Colab) and no explicit command-line arguments are passed
    is_interactive_colab = 'ipykernel' in sys.modules or hasattr(sys, 'ps1')

    if is_interactive_colab and len(sys.argv) == 1:
        print("Note: Ce bloc est conçu pour une exécution en ligne de commande.\n")
        print("Pour tester la fonction dans cet environnement interactif (Colab), vous pouvez l'appeler directement.\n")
        print("Exemple d'utilisation directe dans Colab :\n")
        print("  # Assurez-vous d'avoir un fichier CSV de test approprié et le fichier modèle dans votre environnement Colab")
        print("  # Ex: csv_file_path_for_test = 'billets_test.csv'")
        print("  # Ex: model_file_path_for_test = 'best_logistic_regression_model.joblib'\n")
        print("  # predictions_df_result = predict_bill_authenticity_from_csv(csv_file_path_for_test, model_file_path_for_test)\n")
        print("  # if not predictions_df_result.empty: ipython_display(predictions_df_result.head())\n")
    else:
        # Proceed with argparse if it's a command-line execution or explicit arguments are given
        try:
            args = parser.parse_args()

            print(f"Début de la prédiction pour le fichier: {args.csv_path}")
            predictions_df = predict_bill_authenticity_from_csv(args.csv_path, args.model_path)

            if not predictions_df.empty:
                print("Prédictions terminées. Aperçu des résultats:")
                # Use print for command-line output
                print(predictions_df.head())

                output_file = 'predictions.csv'
                predictions_df.to_csv(output_file, index=False)
                print(f"Les prédictions ont été sauvegardées dans '{output_file}'.")
            else:
                print("Aucune prédiction n'a pu être générée.")
        except SystemExit as e:
            # This catches SystemExit which argparse can raise (e.g., if required args are missing)
            if e.code != 0: # Only print error if it's not a normal exit (like --help)
                print(f"Erreur lors du parsing des arguments en ligne de commande: Le code de sortie était {e.code}")
                print("Veuillez vous assurer de fournir les arguments requis, par exemple:")
                print("python votre_script.py --csv_path chemin/vers/votre_fichier.csv --model_path chemin/vers/votre_modele.joblib")
